export const REMOVE_REFERENCIADO = 'REMOVE_REFERENCIADO'
export const ADD_REFERENCIADO = 'ADD_REFERENCIADO'
export const SAVE_REFERENCIADOS = 'SAVE_REFERENCIADOS'
export const REFERENCIADOR_ACCESO = 'REFERENCIADOR_ACCESO'